sonar.projectKey=Aniol0012_tikz-drawer
sonar.projectName=tikz-drawer
sonar.organization=${env.SONAR_ORGANIZATION}

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/dist/**
sonar.cpd.exclusions=**/*.html

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S7780
